"""
Policy generation and validation utilities.

Generate Rego policy skeletons from FastAPI routes and validate policies at startup.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any, Callable, cast

from ._policy import _compile_policy_groups, _resolve_policy_path, scan_policy_files

if TYPE_CHECKING:
    from fastapi import FastAPI
    from fastapi.routing import APIRoute

    from .dependencies import TopazConfig

__all__ = [
    "generate_policies",
    "generate_rights_matrix",
    "policy_diff",
    "PolicyTemplate",
    "PolicyDiff",
    "MissingPolicy",
    "RouteResolution",
    "ValidationResult",
]


@dataclass
class PolicyTemplate:
    """Configuration for generated Rego policies."""

    default_decision: bool = False
    include_comments: bool = True
    include_route_info: bool = True
    include_input_schema: bool = True
    include_ds_check: bool = True  # For ReBAC


@dataclass
class MissingPolicy:
    """Information about a missing policy."""

    policy_path: str
    method: str
    path: str
    route_pattern: str
    auth_type: str  # "policy" or "rebac"


@dataclass
class PolicyDiff:
    """Result of comparing routes against policies."""

    missing: list[MissingPolicy] = field(default_factory=list)
    orphaned: list[str] = field(default_factory=list)
    valid: list[str] = field(default_factory=list)
    group_covered: list[str] = field(default_factory=list)
    default_covered: list[str] = field(default_factory=list)

    @property
    def has_issues(self) -> bool:
        return len(self.missing) > 0 or len(self.orphaned) > 0


@dataclass
class ValidationResult:
    """Result of policy validation."""

    valid: bool
    total_routes: int
    total_policies: int
    missing_policies: list[MissingPolicy] = field(default_factory=list)
    orphaned_policies: list[str] = field(default_factory=list)
    validated_policies: list[str] = field(default_factory=list)


def _extract_path_params(path: str) -> list[str]:
    """Extract path parameter names from a route path."""
    return re.findall(r"\{(\w+)\}", path)


def _generate_policy_rego(
    policy_path: str,
    route_path: str,
    method: str,
    template: PolicyTemplate,
    is_rebac: bool = False,
) -> str:
    """Generate Rego policy content."""
    lines = [f"package {policy_path}", "", "import rego.v1", ""]

    default_val = "true" if template.default_decision else "false"
    lines.append(f"default allowed = {default_val}")
    lines.append("")

    if template.include_comments and template.include_route_info:
        lines.append(f"# Route: {method} {route_path}")
        params = _extract_path_params(route_path)
        if params:
            lines.append(f"# Path params: {', '.join(params)}")
        lines.append(f"# Auth type: {'rebac' if is_rebac else 'policy'}")
        lines.append("# Generated by fastapi-topaz")
        lines.append("#")

    if template.include_comments and template.include_input_schema:
        lines.append("# Available input:")
        lines.append('#   - input.identity.type: Identity type (e.g., "IDENTITY_TYPE_SUB")')
        lines.append("#   - input.identity.value: User ID")
        if is_rebac:
            lines.append('#   - input.resource.object_type: Resource type (e.g., "document")')
            lines.append("#   - input.resource.object_id: Resource ID")
            lines.append('#   - input.resource.relation: Relation to check (e.g., "can_write")')
            lines.append('#   - input.resource.subject_type: Subject type (default: "user")')
        else:
            for param in _extract_path_params(route_path):
                lines.append(f"#   - input.resource.{param}: Value of {{{param}}} path parameter")
        lines.append("")

    if is_rebac and template.include_ds_check:
        lines.extend(
            [
                "allowed if {",
                "    ds.check({",
                '        "object_type": input.resource.object_type,',
                '        "object_id": input.resource.object_id,',
                '        "relation": input.resource.relation,',
                '        "subject_type": input.resource.subject_type,',
                '        "subject_id": input.identity.value,',
                "    })",
                "}",
            ]
        )
    else:
        lines.extend(
            [
                "allowed if {",
                "    # TODO: Implement authorization logic",
                '    input.identity.type == "IDENTITY_TYPE_SUB"',
                "}",
            ]
        )

    return "\n".join(lines) + "\n"


DEFAULT_EXCLUDE_PATHS = {
    "/openapi.json",
    "/docs",
    "/docs/oauth2-redirect",
    "/redoc",
}


def scan_routes(
    app: FastAPI,
    policy_root: str,
    exclude_paths: set[str] | None = None,
    policy_path_normalizer: Callable[[str], str] | None = None,
) -> list[dict[str, Any]]:
    """
    Scan FastAPI app routes and extract policy information.

    Args:
        app: FastAPI application instance
        policy_root: Policy path root
        exclude_paths: Paths to exclude (defaults to docs routes)
        policy_path_normalizer: Optional callable applied to generated policy
            paths (must match the runtime config to avoid drift)

    Returns list of route info dicts with policy_path, method, path, etc.
    """
    if exclude_paths is None:
        exclude_paths = DEFAULT_EXCLUDE_PATHS

    routes = []
    for route in app.routes:
        if not hasattr(route, "methods") or not hasattr(route, "path"):
            continue

        api_route = cast("APIRoute", route)
        path = api_route.path
        if path in exclude_paths:
            continue

        for method in api_route.methods or []:
            if method in ("HEAD", "OPTIONS"):
                continue

            policy_path = _resolve_policy_path(policy_root, method, path, policy_path_normalizer)
            routes.append(
                {
                    "policy_path": policy_path,
                    "method": method,
                    "path": path,
                    "route_pattern": path,
                    "auth_type": "policy",  # Default, could be detected from dependencies
                }
            )

    return routes


def generate_policies(
    app: FastAPI,
    config: TopazConfig,
    output_dir: str | Path | None = None,
    template: PolicyTemplate | None = None,
) -> dict[str, str]:
    """
    Generate Rego policy skeletons from FastAPI routes.

    Args:
        app: FastAPI application instance
        config: TopazConfig with policy_path_root
        output_dir: Optional directory to write policy files
        template: Optional template configuration

    Returns:
        Dict mapping policy paths to Rego content
    """
    template = template or PolicyTemplate()
    routes = scan_routes(
        app,
        config.policy_path_root,
        policy_path_normalizer=config.policy_path_normalizer,
    )
    policies: dict[str, str] = {}

    for route_info in routes:
        policy_path = route_info["policy_path"]
        rego = _generate_policy_rego(
            policy_path,
            route_info["path"],
            route_info["method"],
            template,
            is_rebac=route_info["auth_type"] == "rebac",
        )
        policies[policy_path] = rego

    # Generate ReBAC check policy
    rebac_path = f"{config.policy_path_root}.check"
    policies[rebac_path] = _generate_policy_rego(
        rebac_path, "/check", "CHECK", template, is_rebac=True
    )

    if output_dir:
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        for policy_path, content in policies.items():
            file_path = output_path / f"{policy_path.replace('.', '/')}.rego"
            file_path.parent.mkdir(parents=True, exist_ok=True)
            file_path.write_text(content)

    return policies


def policy_diff(
    app: FastAPI,
    config: TopazConfig,
    policies_dir: str | Path,
) -> PolicyDiff:
    """
    Compare FastAPI routes against existing policy files.

    When ``config`` has ``policy_groups`` or ``default_policy`` set, routes
    without an explicit ``.rego`` file are classified as *group-covered* or
    *default-covered* instead of *missing* — provided the referenced policy
    file actually exists in *policies_dir*.

    Args:
        app: FastAPI application instance
        config: TopazConfig with policy_path_root
        policies_dir: Directory containing .rego policy files

    Returns:
        PolicyDiff with missing, orphaned, valid, group_covered, and
        default_covered policies
    """
    routes = scan_routes(
        app,
        config.policy_path_root,
        policy_path_normalizer=config.policy_path_normalizer,
    )
    route_policies = {r["policy_path"] for r in routes}
    route_policies.add(f"{config.policy_path_root}.check")  # ReBAC policy
    # Resolution-chain policies are referenced by config, not routes — not orphans
    if config.default_policy:
        route_policies.add(config.default_policy)
    for group in config.policy_groups:
        route_policies.add(group.policy_path)

    existing_policies = scan_policy_files(policies_dir)

    # Pre-compile group patterns for matching
    compiled_groups = _compile_policy_groups(config.policy_groups)

    diff = PolicyDiff()

    for route_info in routes:
        policy_path = route_info["policy_path"]
        route_path = route_info["route_pattern"]

        if policy_path in existing_policies:
            diff.valid.append(policy_path)
            continue

        # Check if covered by a policy group
        group_match = False
        for compiled_pattern, group_policy_path in compiled_groups:
            if compiled_pattern.match(route_path) and group_policy_path in existing_policies:
                diff.group_covered.append(policy_path)
                group_match = True
                break

        if group_match:
            continue

        # Check if covered by default policy
        if config.default_policy and config.default_policy in existing_policies:
            diff.default_covered.append(policy_path)
            continue

        diff.missing.append(
            MissingPolicy(
                policy_path=policy_path,
                method=route_info["method"],
                path=route_info["path"],
                route_pattern=route_info["route_pattern"],
                auth_type=route_info["auth_type"],
            )
        )

    # Check ReBAC policy
    rebac_path = f"{config.policy_path_root}.check"
    if rebac_path in existing_policies:
        diff.valid.append(rebac_path)
    elif config.default_policy and config.default_policy in existing_policies:
        diff.default_covered.append(rebac_path)
    else:
        diff.missing.append(
            MissingPolicy(
                policy_path=rebac_path,
                method="CHECK",
                path="/check",
                route_pattern="/check",
                auth_type="rebac",
            )
        )

    # Find orphaned policies
    for policy in existing_policies:
        if policy not in route_policies:
            diff.orphaned.append(policy)

    return diff


@dataclass(frozen=True)
class RouteResolution:
    """Resolution result for a single route — used by :func:`generate_rights_matrix`."""

    method: str
    route_pattern: str
    specific_policy_path: str
    resolved_policy_path: str
    resolution_source: str  # "explicit" | "group" | "default" | "generated"
    matched_group_pattern: str | None
    policy_file_exists: bool


def generate_rights_matrix(
    app: FastAPI,
    config: TopazConfig,
    policies_dir: str | Path | None = None,
    output_file: str | Path | None = None,
) -> list[RouteResolution]:
    """
    Generate a comprehensive rights matrix resolving every route through the
    policy resolution chain.

    Produces a list of :class:`RouteResolution` entries and optionally writes
    a Markdown summary to *output_file*.

    Args:
        app: FastAPI application instance
        config: TopazConfig with policy_path_root (and optional
            default_policy / policy_groups)
        policies_dir: Directory containing ``.rego`` policy files (optional)
        output_file: Path to write Markdown output (optional)

    Returns:
        List of RouteResolution entries for every discovered route.
    """
    routes = scan_routes(
        app,
        config.policy_path_root,
        policy_path_normalizer=config.policy_path_normalizer,
    )
    existing: set[str] = scan_policy_files(policies_dir) if policies_dir else set()

    compiled_groups = _compile_policy_groups(config.policy_groups)

    results: list[RouteResolution] = []

    for route_info in routes:
        specific = route_info["policy_path"]
        route_path = route_info["route_pattern"]
        resolved = specific
        source = "generated"
        matched_pattern: str | None = None

        # Resolution chain
        if policies_dir is not None and specific in existing:
            resolved, source = specific, "explicit"
        else:
            for compiled_pattern, group_pp in compiled_groups:
                if compiled_pattern.match(route_path):
                    resolved, source = group_pp, "group"
                    matched_pattern = compiled_pattern.pattern
                    break
            if source == "generated" and config.default_policy:
                resolved, source = config.default_policy, "default"

        results.append(
            RouteResolution(
                method=route_info["method"],
                route_pattern=route_info["path"],
                specific_policy_path=specific,
                resolved_policy_path=resolved,
                resolution_source=source,
                matched_group_pattern=matched_pattern,
                policy_file_exists=resolved in existing,
            )
        )

    if output_file:
        _write_rights_matrix_markdown(
            results,
            config.policy_path_root,
            Path(output_file),
        )

    return results


def _write_rights_matrix_markdown(
    results: list[RouteResolution],
    policy_root: str,
    output_path: Path,
) -> None:
    """Write the rights matrix as a Markdown document."""
    explicit = [r for r in results if r.resolution_source == "explicit"]
    group = [r for r in results if r.resolution_source == "group"]
    default = [r for r in results if r.resolution_source == "default"]
    unresolved = [r for r in results if r.resolution_source == "generated"]

    lines: list[str] = [
        f"# Rights Matrix — {policy_root}",
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "## Summary",
        f"- Total routes: {len(results)}",
        f"- Explicit policies: {len(explicit)}",
        f"- Group-covered: {len(group)}",
        f"- Default-covered: {len(default)}",
        f"- **Unresolved: {len(unresolved)}**",
        "",
        "## Routes by Resolution Source",
        "",
        "| Method | Route | Resolved Policy | Source | File Exists |",
        "|--------|-------|-----------------|--------|-------------|",
    ]

    for r in sorted(results, key=lambda x: (x.route_pattern, x.method)):
        source_label = r.resolution_source
        if r.matched_group_pattern:
            source_label = f"group ({r.matched_group_pattern})"
        exists = "Y" if r.policy_file_exists else "N"
        lines.append(
            f"| {r.method} | {r.route_pattern} | "
            f"{r.resolved_policy_path} | {source_label} | {exists} |"
        )

    lines.append("")
    output_path.write_text("\n".join(lines))
