# Get default certificate for signing
data "authentik_certificate_key_pair" "generated" {
  name = "authentik Self-signed Certificate"
}

# Get default flows
data "authentik_flow" "authorization_flow" {
  slug = "default-provider-authorization-implicit-consent"
}

data "authentik_flow" "invalidation_flow" {
  slug = "default-provider-invalidation-flow"
}

data "authentik_flow" "authentication_flow" {
  slug = "default-authentication-flow"
}

# Get default scope mappings by name
data "authentik_property_mapping_provider_scope" "openid" {
  managed = "goauthentik.io/providers/oauth2/scope-openid"
}

data "authentik_property_mapping_provider_scope" "email" {
  managed = "goauthentik.io/providers/oauth2/scope-email"
}

data "authentik_property_mapping_provider_scope" "profile" {
  managed = "goauthentik.io/providers/oauth2/scope-profile"
}

# Create OIDC provider for webapp
resource "authentik_provider_oauth2" "webapp" {
  name               = "webapp-provider"
  client_id          = "webapp-client"
  authorization_flow = data.authentik_flow.authorization_flow.id
  invalidation_flow  = data.authentik_flow.invalidation_flow.id

  # Client type - confidential for server-side apps
  client_type = "confidential"

  # Signing key for JWTs
  signing_key = data.authentik_certificate_key_pair.generated.id

  # Allowed redirect URIs
  allowed_redirect_uris = [
    {
      matching_mode = "strict"
      url           = var.webapp_redirect_uri
    }
  ]

  # Property mappings (scopes)
  property_mappings = [
    data.authentik_property_mapping_provider_scope.openid.id,
    data.authentik_property_mapping_provider_scope.email.id,
    data.authentik_property_mapping_provider_scope.profile.id
  ]

  # Access token validity
  access_token_validity = "hours=1"
  refresh_token_validity = "days=30"
}

# Create application
resource "authentik_application" "webapp" {
  name              = "FastAPI Aserto Test Webapp"
  slug              = "webapp"
  protocol_provider = authentik_provider_oauth2.webapp.id

  # Optional: set icon
  meta_icon         = "https://fastapi.tiangolo.com/img/icon-white.svg"
  meta_description  = "Test application for FastAPI-Aserto ABAC capabilities"

  # Make it visible in the user interface
  open_in_new_tab   = false
}

# Create test users
resource "authentik_user" "test_users" {
  for_each = { for u in var.test_users : u.username => u }

  username   = each.value.username
  name       = each.value.name
  email      = each.value.email
  password   = each.value.password

  attributes = jsonencode({
    settings = {
      locale = "en"
    }
  })
}

# Create a test group
resource "authentik_group" "test_users" {
  name = "Test Users"
  users = [
    for user in authentik_user.test_users : user.id
  ]
}

# Optional: Create policies for application access
resource "authentik_policy_binding" "webapp_access" {
  target = authentik_application.webapp.uuid
  group  = authentik_group.test_users.id
  order  = 0
}

# Write OIDC credentials to env file for docker-compose
resource "local_file" "oidc_env" {
  filename = "${path.module}/../../../.env.oidc"
  content  = <<-EOT
# Auto-generated by Terraform - do not edit manually
OIDC_CLIENT_ID=${authentik_provider_oauth2.webapp.client_id}
OIDC_CLIENT_SECRET=${authentik_provider_oauth2.webapp.client_secret}
EOT
  file_permission = "0600"
}
